backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - name: "data"
        label: "Main Content"
        file: "content/data.json"
        fields:
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Text", name: "text", widget: "text" }

          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - { label: "Sneaker Name", name: "name", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }

          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Instagram", name: "instagram", widget: "string" }
